Write-Host "Current workflow:"
Write-Host "1. Open XRPL Hooks Builder in the browser."
Write-Host "2. Paste the local source from contracts/src into the Builder."
Write-Host "3. Compile and deploy to Devnet."
Write-Host "4. Keep the Builder version synced back into this repo."
Write-Host ""
Write-Host "First milestone target:"
Write-Host "- pay_and_claim writes claim state from HookParameters"
Write-Host "- claim_ticket reads HookState and emits a real transfer"
